import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import Img from "../public/vishnu.jpeg";
import Design from "../public/design.png";
import Code from "../public/code.png";
import Consulting from "../public/consulting.png";
import Web1 from "../public/web1.png";
import Web2 from "../public/web2.png";
import Web3 from "../public/web3.png";
import Web4 from "../public/web4.png";
import Web5 from "../public/web5.png";
import Web6 from "../public/web6.png";
import { useState } from "react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Link from "next/link";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>{`Vishnu Sekhar\u0027s Portfolio`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 xl:px-100 dark:bg-gray-900">
        <section className="min-h-screen">
          <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
          <div className="text-center p-1">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Vishnu Sekhar
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Software Developer</h3>
            <p className="text-justify text-md py-5 leading-relaxed text-gray-800 md:text-xl max-w-xl mx-auto">
              A highly skilled software developer with 2 years of experience
              specializing in web and mobile application development. With a
              strong focus on front-end technologies, have extensive proficiency
              in React, React Native, JavaScript, TypeScript, and version
              control tools like Git.
            </p>
          </div>
          <div className="text-5xl flex justify-between gap-12 py-3 px-1 text-gray-600">
            <AiFillTwitterCircle />
            <a
              target="blank"
              rel="noopener noreferrer"
              href="https://www.linkedin.com/in/itsvishnusekhar/"
            >
              <AiFillLinkedin className="cursor-pointer" />
            </a>
            <a
              target="blank"
              rel="noopener noreferrer"
              href="https://github.com/seVishnu"
            >
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 sm:w-80 sm:h-80 my-14 overflow-hidden md:w-96 md:h-96">
            <Image
              src={Img}
              layout="fill"
              objectFit="cover"
              alt="display picture"
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              flex, pt-4, text-center and rotate-90 that can be composed to
              build any design, directly in your markup.
              <span className="text-teal-500">
                {" "}
                text-center and rotate-90 that can
              </span>
              composed to<span className="text-teal-500">build</span>any design
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              flex, pt-4, text-center and rotate-90 that can be composed to
              build any design, directly in your markup.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div>
                <Image src={Design} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2">
                  Beautiful Designs
                </h3>
                <p className="py-2">
                  Creating elegant designs suited for your needs.
                </p>
                <h4 className="py-4 text-teal-600">Design tools I use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">Dream Weaver</p>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div>
                <Image src={Code} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2">
                  Beautiful Designs
                </h3>
                <p className="py-2">
                  Creating elegant designs suited for your needs.
                </p>
                <h4 className="py-4 text-teal-600">Design tools I use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">Dream Weaver</p>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <div>
                <Image src={Consulting} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2">
                  Beautiful Designs
                </h3>
                <p className="py-2">
                  Creating elegant designs suited for your needs.
                </p>
                <h4 className="py-4 text-teal-600">Design tools I use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Figma</p>
                <p className="text-gray-800 py-1">Dream Weaver</p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              flex, pt-4, text-center and rotate-90 that can be composed to
              build any design, directly in your markup.
              <span className="text-teal-500">
                {" "}
                text-center and rotate-90 that can
              </span>
              composed to<span className="text-teal-500">build</span>any design
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              flex, pt-4, text-center and rotate-90 that can be composed to
              build any design, directly in your markup.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={Web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={Web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={Web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={Web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={Web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={Web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
        <Footer />
      </main>
    </div>
  );
}
