import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from 'react-icons/ai'
import Image from 'next/image'
import Img from '../public/dev-ed-wave.png'
import Design from '../public/design.png'
import Code from '../public/code.png'
import Consulting from '../public/consulting.png'
import Web1 from '../public/web1.png'
import Web2 from '../public/web2.png'
import Web3 from '../public/web3.png'
import Web4 from '../public/web4.png'
import Web5 from '../public/web5.png'
import Web6 from '../public/web6.png'
import { useState } from 'react'
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Susan Tarkowski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 xl:px-100 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>devHound</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick = {()=> setDarkMode(!darkMode)} className='cursor-pointer text-2xl' /></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Susan Tarkowski</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>A utility-first CSS framework packed with classes like
              flex, pt-4, text-center and rotate-90 that can be
              composed to build any design, directly in your markup.</p>
          </div>
          <div className='text-5xl flex justify-between gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96'>
            <Image src={Img} layout='fill' objectFit='cover' />
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>flex, pt-4, text-center and rotate-90 that can be
              composed to build any design, directly in your markup.
              <span className='text-teal-500'> text-center and rotate-90 that can</span>composed to<span className='text-teal-500'>build</span>any design
            </p>
            <p className='text-md py-2 leading-8 text-gray-800'>flex, pt-4, text-center and rotate-90 that can be
              composed to build any design, directly in your markup.</p>
          </div>
          <div className='lg:flex gap-10'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <div><Image src={Design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your needs.</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Dream Weaver</p>
              </div>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <div><Image src={Code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your needs.</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Dream Weaver</p>
              </div>
          </div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <div><Image src={Consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your needs.</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Dream Weaver</p>
              </div>
          </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>flex, pt-4, text-center and rotate-90 that can be
              composed to build any design, directly in your markup.
              <span className='text-teal-500'> text-center and rotate-90 that can</span>composed to<span className='text-teal-500'>build</span>any design
            </p>
            <p className='text-md py-2 leading-8 text-gray-800'>flex, pt-4, text-center and rotate-90 that can be
              composed to build any design, directly in your markup.</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={Web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={Web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={Web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={Web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={Web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={Web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'  />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
